### ISSUE TITLE
how to view the parameters

### ISSUE THREAD

**Issue by nvliajia** [pltrees/abcboost#3]
If I have trained a model and saved it, how can I view the ranking of parameters and feature importance of the model

**Comment by pltrees** [comment]
Hi, nvliajia

add "-save_importance 1"  and you will see a ".importance" file.

**Comment by nvliajia** [comment]
I run './abcboost_train -method robustlogit -data ./data/ijcnn1.train.csv -J 20 -v 0.1 -iter 10000 -save_importance 1' but get Unknown argument [save_importance]

**Comment by pltrees** [comment]
Hi, nvliajia

Could you do a git pull and re-compile the code? Thanks.

**Comment by nvliajia** [comment]
I just run your demo for binary classification problem code.
![1660610318840](https://user-images.githubusercontent.com/59531363/184776844-ec326e47-71a5-4cf1-99b9-e4775a869ec0.png)
and add -save_importance 1 then I got error Unknown argument [save_importance]

**Comment by pltrees** [comment]
> I just run your demo for binary classification problem code. ![1660610318840](https://user-images.githubusercontent.com/59531363/184776844-ec326e47-71a5-4cf1-99b9-e4775a869ec0.png) and add -save_importance 1 then I got error Unknown argument [save_importance]

hello, please do a git pull and build again. Thank you.
